
project_id = "zknyyltinlagwkbbedrx"

[functions.ai-lead-scoring]
verify_jwt = true

[functions.analytics-report]
verify_jwt = true

[functions.lead-auto-assign]
verify_jwt = true

[functions.batch-operations]
verify_jwt = true

[functions.execute-workflow]
verify_jwt = true

[functions.send-notification-email]
verify_jwt = true

[functions.api]
verify_jwt = false
